### Rota para criar o orçamento
POST http://localhost:3000/orcamentos
Content-Type: application/json

{
    "nome_cliente":"Maria",
    "descricao": "Pintura de um quarto",
    "valor": 200, 
    "prazo": "20/03/2025", 
    "status": "aprovado",
    "data_criacao": "10/03/2025"
}

### 

### Rota para pegar/mostrar os orçamentos criados
GET http://localhost:3000/orcamentos
Content-Type: application/json

### 

### Rota para buscar orçamento específico pelo id
GET http://localhost:3000/orcamentos/4
Content-Type: application/json

###

### Rota para editar um orçamento
PUT http://localhost:3000/orcamentos/4
Content-Type: application/json

{
    "novoNomeCliente":"João Paulo Silva",
    "novaDescricao": "Pintura de um apartamento de 80m²",
    "novoValor": 400, 
    "novoPrazo": "20/03/2025",
    "novoStatus": "pendente",
    "novaDataCriacao": "10/03/2025"
}

### 

### Rota para Deletar um orçamento pelo id
DELETE http://localhost:3000/orcamentos/4
Content-Type: application/json

###

### Deletar todos os produtos
DELETE http://localhost:3000/orcamentos
Content-Type: application/json

###